/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: J.A (https://sketchfab.com/jossus)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/speaker-jbl-go-3-portable-8587d39f1c404c039eb8df77ef1b8114
title: SPEAKER JBL GO 3 PORTABLE
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

const ModelJbl = (props) => {
    const { nodes, materials } = useGLTF('/jbl.gltf');
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Plane015_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Cube021_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Cube022_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Plane016_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Plane017_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Plane019_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Cube025_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Cube023_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Cube026_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Plane018_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Cube034_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                    <group position={[-90.62, -32.06, 0.85]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <mesh geometry={nodes.Cube024_JBL_Material_0.geometry} material={materials.JBL_Material} />
                    </group>
                </group>
            </group>
        </group>
    );
};
export default ModelJbl;
useGLTF.preload('/jbl.gltf');
